version: '3.4'

services:
  catalogdb:
    image: mongo
services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile


volumes:
  mongo_data: